defaults:
  - default.yaml

tag: 'causal-agents'

# NOTE: for training and validation, this uses the re-split original (unmodified) scenarios.
train_data_path: [ "${paths.base_path}/processed/causal_agents/original/training" ] # list of paths to the training data
train_data_tag: ["causal-agents-original-training"]
val_data_path: ["${paths.base_path}/processed/causal_agents/original/validation" ] # list of paths to the validation data
val_data_tag: ["causal-agents-original-validation"]

# NOTE: for testing, this uses the re-split original scenes and their perturbed (remove_noncausal) counterparts.
test_data_path: [
  "${paths.base_path}/processed/causal_agents/original/validation",
  "${paths.base_path}/processed/causal_agents/original/testing",
  "${paths.base_path}/processed/causal_agents/remove_noncausal/validation",
  "${paths.base_path}/processed/causal_agents/remove_noncausal/testing",
]
test_data_tag: [
  "causal-agents-original-validation",
  "causal-agents-original-testing",
  "remove-noncausal-validation",      # Perturbation: removes agents that are NOT causal to the ego.
  "remove-noncausal-testing",
]
