defaults:
 - default.yaml

viz_type: model_output
pane_type: non_background_scenario  # override: non-background predictions are model output but get their own folder
visualizer:
  _target_: controlledshifts.utils.scenario_visualizers.scenario_animated.ScenarioAnimatedVisualizer
  config:
    panes_to_plot:
      - HIGHLIGHT_RELEVANT
      - NON_BACKGROUND_AGENTS_GT
      - NON_BACKGROUND_AGENTS_PRED
