defaults:
 - default.yaml

viz_type: model_output
pane_type: causal_scenario  # override: causal predictions are model output but get their own folder
visualizer:
  _target_: controlledshifts.utils.scenario_visualizers.scenario.ScenarioVisualizer
  config:
    panes_to_plot:
      - ALL_AGENTS
      - NON_BACKGROUND_AGENTS_GT
      - NON_BACKGROUND_AGENTS_PRED
