defaults:
 - default.yaml

viz_type: regular
visualizer:
  _target_: controlledshifts.utils.scenario_visualizers.scenario_animated.ScenarioAnimatedVisualizer
  config:
    panes_to_plot:
      - HIGHLIGHT_RELEVANT
