defaults:
 - default.yaml

viz_type: trajpred
visualizer:
  _target_: controlledshifts.utils.scenario_visualizers.scenario_trajpred.ScenarioTrajpredVisualizer
  config:
    is_ego_centric: true
    panes_to_plot:
      - TRAJECTORY_PREDICTION
